language: cpp

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake3 libboost-system-dev realpath
  - curl https://www.openssl.org/source/openssl-1.0.2n.tar.gz | tar xz
  - cd openssl-1.0.2n/
  - ./config shared
  - make
  - sudo make install
  - cd ../

script:
  - mkdir build
  - cd build/
  - cmake -DOPENSSL_ROOT_DIR="/usr/local/ssl/" ..
  - make
  - ctest
  - sudo make install

addons:
  artifacts: true
