language: cpp

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake3 libboost-system-dev realpath mingw-w64 gcc-mingw-w64 g++-mingw-w64
  - curl https://cfhcable.dl.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.tar.gz | tar xz
  - cd boost_1_54_0/
  - "echo using gcc : : i686-w64-mingw32-g++ ; > user-config.jam"
  - ./bootstrap.sh
  - ./b2 --user-config=user-config.jam toolset=gcc target-os=windows release
  - cd ../
  - curl https://www.openssl.org/source/openssl-1.0.2n.tar.gz | tar xz
  - cd openssl-1.0.2n/
  - ./config shared
  - make
  - sudo make install
  - cd ../

script:
  - mkdir build
  - cd build/
  - cmake -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR="/usr/local/ssl/" ..
  - make
  - ctest
  - sudo make install

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "trojan"
  skip_cleanup: true
  on:
    tags: true
